;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI.Profile.Melee.Grunt",DevComment="近战小兵的画像标签")
+GameplayTagList=(Tag="AI.Profile.MeleeGrunt",DevComment="刀战近战步兵")
+GameplayTagList=(Tag="AI.Profile.MeleeRusher",DevComment="近战配置")
+GameplayTagList=(Tag="Faction.Enemy",DevComment="敌方阵营")
+GameplayTagList=(Tag="Faction.FriendlyAI",DevComment="友好AI阵营标签")
+GameplayTagList=(Tag="Faction.Hostile",DevComment="敌对")
+GameplayTagList=(Tag="Faction.Hostile.All",DevComment="所有敌对目标")
+GameplayTagList=(Tag="Faction.Neutral",DevComment="中立")
+GameplayTagList=(Tag="Faction.Player",DevComment="玩家阵营标签，用于AI敌友判定")
+GameplayTagList=(Tag="Faction.Zombie",DevComment="丧尸/怪物阵营标签")

